spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml   # config-location을 설정
  mapper-locations: classpath:mapper/*.xml  # Mapper XML 파일 위치 설정
  type-aliases-package: com.soccer.user.entity  # Entity 클래스 패키지 지정

server:
  port: 8080
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG

