spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    root: ERROR
    ssb.soccer: DEBUG

gpt:
  api:
    key: "your-api-key"


server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never
